# Generated by Django 4.2.1 on 2023-06-03 07:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'verbose_name': 'Normal User',
                'verbose_name_plural': 'Normal Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.models.NormalUserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='supportstaff',
            options={'verbose_name': 'Support Staff', 'verbose_name_plural': 'Support Staff'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_supportstaff',
            field=models.BooleanField(default=False),
        ),
    ]
