# Generated by Django 4.1.7 on 2023-06-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_normaluser_alter_supportstaff_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportStaff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_supportstaff',
        ),
    ]
